#!/usr/local/bin/node

const { execSync } = require("child_process");
const { name } = require('./package.json');

// const commit = execSync("git show -s --format=%h").toString().trim();

// 上传静态资源到 cos 对象存储
const uploadToCos = (path) => {
  execSync(`coscmd -c ~/.cos.t-iiot.conf upload -rs ./dist/ /hat/${path}`);
};

// 唯一入口函数
const entry = () => {
  const currentDir = process.cwd();
  console.log('当前目录', currentDir)
  console.log('项目名字', name);
  uploadToCos(name);
};

if (require.main === module) {
  entry();
}
